---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What is Tenant name to be delete?"
      private: no

  tasks:
    - name: Delete a tenant
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        method: "delete"
        validate_certs: False
        tenant: "{{ tenant }}"
        state: absent
