---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What is your Tenant name?"
      private: no

  tasks:
    - name: Query All Bridge Domains
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: query
        tenant: "{{ tenant }}"
      register: query_result

    - debug:
        msg: "{{ query_result.current|json_query('[].fvTenant.children[].fvBD.attributes.name') }}"
